# -*- coding: utf-8 -*-
"""Assignment_4B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TgSbaRP431pV-8SMdmXlZ76wsSjg91hx
"""

import pandas as pd
import numpy as np
data=pd.read_csv('groundwater_survey.csv')

"""# New Section"""

data.skew()

log_X=np.log(np.log(np.log(data['X'])))
log_X.skew()

print(data)

x_train=data.iloc[0:30,0]
y_train=data.iloc[0:30,0]
x_test=data.iloc[30:34,1]
y_test=data.iloc[30:35,1]

x_train=x_train.iloc[1:].values
x_train=x_train.reshape(len(x_train),1)
y_train=y_train.iloc[1:].values
y_train=y_train.reshape(len(y_train),1)
x_test=x_test.iloc[1:].values
x_test=x_test.reshape(len(x_test),1)
y_test=y_test.iloc[1:].values
y_test=y_test.reshape(len(y_test),1)

def slr_sgd(x,y,epochs):
    length=len(x)
    i=0
    j=0
    m=[1]*(length)
    c=[1]*(length)
    a1=[]
    a2=[]
    y_pre=[]
    while(j<epochs):
        while(i<length):
            k=(y[i]-(m[i]*x[i])-c[i])
            dm=-0.01*(k*x[i])
            dc=-0.01*k
            m[i]=m[i]+dm
            c[i]=c[i]+dc
            a1.append(m[i])
            a2.append(c[i])
            i=i+1
        j=j+1
    return a1,a2

m,c=slr_sgd(x_train,y_train,2)
print(m)
print(c)

i=0
y_pred=[]
while i<29:
    y_predict=(m[i]*x_train[i])-c[i]
    y_pred.append(y_predict)
    i=i+1

print(y_pred)

import math
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import mean_absolute_error

def accuracy_op(y_train,y_pred):
    mse = math.sqrt(mean_squared_error(y_train,y_pred)) 
    print('Root mean square error', mse) 
    mse = (mean_squared_error(y_train,y_pred)) 
    print('Mean square error', mse) 
    mae=mean_absolute_error(y_train, y_pred)
    print('Mean absolute error', mae)

print(accuracy_op(y_train,y_pred))

m1,c1=slr_sgd(x_test,y_test,2)
print(m1,c1)

i=0
yt_pred=[]
while i<3:
    yt_predict=(m1[i]*x_test[i])-c1[i]
    yt_pred.append(yt_predict)
    i=i+1

print(yt_pred)

print(accuracy_op(y_test,yt_pred))